package com.sionsmith.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

/**
 * Created by sionsmith on 20/05/2014.
 */
@DynamoDBTable(tableName = "connection")
public class Contact {

    private String contactId;
    private String firstName;
    private String lastName;
    private String imageId;
    private String  test;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId()
    {
        return contactId;
    }

    @DynamoDBAttribute
    public String getFirstName()
    {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName()
    {
        return lastName;
    }

    @DynamoDBAttribute
    public String getImageId() {
        return imageId;
    }

    public String imageId(){ return imageId; }
    public Contact(String firstName, String lastName) {
        this.firstName = firstName;
        this.lastName = lastName;
    }

    public void setId(String id) {
        this.contactId = id;
    }

    public Contact() {
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setImageId(String imageId) {
        this.imageId = imageId;
    }
}
